# Generated by Django 6.0.8 on 2026-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'capture record',
                'verbose_name_plural': 'Captures',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'Devices',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'People',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='RecognitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'recognition record',
                'verbose_name_plural': 'Recognition',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
