# Generated by Django 6.0.8 on 2026-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'live view',
                'verbose_name_plural': 'Live view',
                'abstract': False,
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
