# Generated by Django 6.0.8 on 2026-09-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxapp', '0004_algorithmpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementAlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_id', models.IntegerField()),
                ('zone_points', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('sensitivity', models.FloatField(default=0.015)),
                ('trigger_frames', models.PositiveIntegerField(default=3)),
                ('cooldown_seconds', models.PositiveIntegerField(default=30)),
                ('alarm_duration_seconds', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='algorithmpackage',
            options={'default_permissions': ('view',), 'managed': False, 'permissions': [('upload_algorithmpackage', 'Can upload algorithm package')], 'verbose_name': 'algorithm package', 'verbose_name_plural': 'Algorithms'},
        ),
        migrations.CreateModel(
            name='MovementAlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('detection_score', models.FloatField(default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='boxapp.movementalarmrule')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
